# use minimal base image
FROM alpine:latest

# install run tools
RUN apk add --no-cache \
    gcc \               # C compiler
    g++ \               # C++ compiler
    python3 \           # Python interpreter
    openjdk11-jre \     # Java runtime
    bash \              # Shell for scripting
    coreutils           # Basic utilities (e.g., timeout)

# set up non-root user
RUN adduser -D judge
USER judge
WORKDIR /home/judge

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]